export const SITE = {
  name: "Allay Medical Solutions",
  legalName: "Allay Medical Solutions, LLC",
  tagline: "Home medical equipment, from neighbors who care.",
  description:
    "Lake Oswego's trusted source for mobility aids, CPAP, bath safety, compression, wound care, incontinence products, and equipment rentals. Serving the Portland metro.",
  url: "https://www.allay-medical.com",
  phoneDisplay: "(971) 233-8121",
  phoneHref: "+19712338121",
  phoneSecondary: "(971) 206-8581",
  email: "info@allay-medical.com",
  address: {
    street: "17394 Boones Ferry Rd",
    city: "Lake Oswego",
    region: "OR",
    postalCode: "97035",
    country: "US",
  },
  geo: {
    latitude: 45.3856,
    longitude: -122.7164,
  },
  hours: [
    { day: "Mon", open: "10:00", close: "18:00" },
    { day: "Tue", open: "10:00", close: "18:00" },
    { day: "Wed", open: "10:00", close: "18:00" },
    { day: "Thu", open: "10:00", close: "18:00" },
    { day: "Fri", open: "10:00", close: "18:00" },
    { day: "Sat", open: "10:00", close: "16:00" },
    { day: "Sun", open: null, close: null },
  ],
  socials: {
    google: "https://www.google.com/maps?q=Allay+Medical+Solutions+Lake+Oswego",
  },
  areasServed: [
    "Lake Oswego",
    "Portland",
    "Tigard",
    "Tualatin",
    "Beaverton",
    "West Linn",
    "Oregon City",
    "Milwaukie",
  ],
} as const;

export const NAV = {
  primary: [
    { label: "Shop", href: "/shop" },
    { label: "Rentals", href: "/rentals" },
    { label: "Book", href: "/appointments" },
    { label: "Services", href: "/services" },
    { label: "Conditions", href: "/conditions" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
  ],
  categories: [
    { label: "Mobility Aids", href: "/shop/mobility-aids" },
    { label: "CPAP & Sleep", href: "/shop/cpap" },
    { label: "Bath Safety", href: "/shop/bath-safety" },
    { label: "Compression", href: "/shop/compression" },
    { label: "Wound Care", href: "/shop/wound-care" },
    { label: "Incontinence", href: "/shop/incontinence" },
    { label: "Daily Living", href: "/shop/daily-living" },
    { label: "PPE", href: "/shop/ppe" },
  ],
  services: [
    { label: "Equipment Rental", href: "/rentals" },
    { label: "Sharps Disposal", href: "/services/sharps-disposal" },
    { label: "Notary Public", href: "/services/notary" },
    { label: "Vaccinations", href: "/services/vaccinations" },
  ],
  conditions: [
    { label: "Sleep Apnea", href: "/conditions/sleep-apnea" },
    { label: "Post-Surgical Recovery", href: "/conditions/post-surgical-recovery" },
    { label: "Mobility Support", href: "/conditions/mobility-support" },
    { label: "Caring for an Elderly Parent", href: "/conditions/caring-for-elderly-parent" },
    { label: "Incontinence Management", href: "/conditions/incontinence-management" },
    { label: "At-Home Wound Care", href: "/conditions/at-home-wound-care" },
    { label: "Bariatric Support", href: "/conditions/bariatric-support" },
  ],
  legal: [
    { label: "Privacy Policy", href: "/privacy" },
    { label: "Accessibility", href: "/accessibility" },
    { label: "Returns", href: "/returns" },
    { label: "Shipping", href: "/shipping" },
    { label: "HIPAA Notice", href: "/hipaa" },
  ],
} as const;
